import 'package:equatable/equatable.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:food_delivery_application/features/category/domain/entity/category_entity.dart';

part 'category_api_model.g.dart';

@JsonSerializable()
class CategoryApiModel extends Equatable {
  @JsonKey(name: '_id')
  final String? id;
  final String name;
  final String description;
  final String image;
  final DateTime? createdAt;

  const CategoryApiModel({
    this.id,
    required this.name,
    required this.description,
    required this.image,
    this.createdAt,
  });

  /// **1. fromJson** - Automatically generated by json_serializable
  factory CategoryApiModel.fromJson(Map<String, dynamic> json) =>
      _$CategoryApiModelFromJson(json);

  /// **2. toJson** - Automatically generated by json_serializable
  Map<String, dynamic> toJson() => _$CategoryApiModelToJson(this);

  /// **Convert API Model to Domain Entity**
  CategoryEntity toEntity() => CategoryEntity(
        id: id,
        name: name,
        description: description,
        image: image,
        createdAt: createdAt,
      );

  /// **Create an API Model from a Domain Entity**
  factory CategoryApiModel.fromEntity(CategoryEntity entity) => CategoryApiModel(
        id: entity.id,
        name: entity.name,
        description: entity.description,
        image: entity.image,
        createdAt: entity.createdAt,
      );

  /// **Convert a List of API Models to a List of Entities**
  static List<CategoryEntity> toEntityList(List<CategoryApiModel> models) =>
      models.map((model) => model.toEntity()).toList();

  @override
  List<Object?> get props => [id, name, description, image, createdAt];
}
